import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>RockPaperScissors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className="h-screen bg-gradient-to-r from-bgColorOne to-bgColorTwo">
      
      </main>
    </>
  )
}
