import Head from 'next/head'
import HomePage from '../components/pages/home-page/home-page'

export default function Home() {
  return (
    <>
      <Head>
        <title>RockPaperScissors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className="h-full bg-gradient-to-r from-bgColorOne to-bgColorTwo md:pt-14 pt-10 font-SemiCondensed font-semibold">
      <HomePage />
      </main>
    </>
  )
}
